Add 'set -e' to bail out during required initial steps.

diff --git a/update-version-wrapper b/update-version-wrapper
--- a/update-version-wrapper
+++ b/update-version-wrapper
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+# This initial setup is essential, so abort if anything fails.
+set -e
+
+orig_dir="$(pwd)"
 export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa.gpii-ci'
 git config --global user.email "gpii-bot@gpii.net"
 git config --global user.name "GPII Bot"
@@ -7,10 +11,12 @@ git config --global user.name "GPII Bot"
 # need those revisions to push to a remote (e.g. gitlab) that hasn't been
 # updated in a bit.
 git clone --depth 10 git@github.com:gpii-ops/gpii-terraform
-orig_dir="$(pwd)"
 cd gpii-terraform/modules/deploy
 git remote add gitlab git@gitlab.com:gpii-ops/gpii-terraform
 
+# Failures in the main loop are ok, so continue if anything fails and try again
+# on the next go around.
+set +e
 while true ; do
     echo "Starting version check at $(date)"
     git fetch --all --tags -p
